[project]
name = "ml-powerlifting-potential"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Swen AUBINEAU", email = "swenaubineau@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
]

[project.scripts]
ml-powerlifting-potential = "ml_powerlifting_potential:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.4.0",
    "pytest>=9.1.1",
    "ruff>=0.16.10",
]
